### PR TITLE
update chat readme

### PR DESCRIPTION
**Pull request by wslack**
cc @konklone

### CODE REVIEW

**Comment by afeld** [comment]
I mean, it's more likely that people will see the broken site than this repository, so not sure that this really helps all that much 😕

**Comment by wslack** [comment]
Should we deploy something to that URL with a similar message - or maybe redirect the URL to this repo for the moment?

**Comment by afeld** [comment]
:+1: on either.

**Comment by afeld** [comment]
Updated the repository description instead, which is more visible. Thanks!

**Pull request closed without merging**
