### PR TITLE
[WIP] Deploy from ci.

### PR DESCRIPTION
**Pull request by jmcarp**
Got nervous about migration progress and started this very simple one. I'm marking as WIP because the secure environment variables, org, and space need to be updated based on where this is going to live, but I verified that this works otherwise.

Resolves https://github.com/18F/cg-migration/issues/55.

cc @suprenant

### CODE REVIEW

**Comment by jmcarp** [comment]
No rush on this, but I'm wondering who's responsible for this application--even trivial apps need an owner 😄. Is it #infrastructure? #admins-slack? @afeld?

**Comment by afeld** [comment]
#wg-opensource, though I have been the main person.

**Comment by jmcarp** [comment]
@afeld: can I assign this to you?

**Review by afeld — APPROVED** [review]

**Comment by afeld** [comment]
> the secure environment variables, org, and space need to be updated based on where this is going to live

It's not deployed in GovCloud yet? I dunno what the org/space should be.

/cc https://github.com/18F/cg-product/issues/523 @suprenant 

> can I assign this to you?

Sure! Anything else that's needed?

**Comment by jmcarp** [comment]
I think the only question left is the one you mentioned, which is where this should live in govcloud. Is there / should there be an org / space for wg-opensource?

**Comment by afeld** [comment]
No strong feelings from me — we can put it wherever cloud.gov wants us. I don't think the working group has anything else on cloud.gov, if that helps.

**Comment by jmcarp** [comment]
@suprenant: any opinion on ☝️ ?

**Comment by suprenant** [comment]
@jmcarp hm, I am not sure. @brittag or @jcscottiii, can you please guide us here?

**Comment by brittag** [comment]
Unfortunately I don't think assigning formal ownership to #wg-opensource is a good idea - the open source working group doesn't have structure or meetings or budget, it's just a chat channel where people sometimes ask and answer questions. I'm more or less the informal lead for #wg-opensource since I established the channel and care about it, and I don't have the technical skill to maintain code projects.

I think we need to figure out who should own this and that person should decide where it goes (or if we can't find a person to claim it, we should shut it down).

**Comment by jcscottiii** [comment]
+1 to @brittag

**Comment by afeld** [comment]
While I totally get the argument for "if it doesn't have an owner, let's shut it down", this "app" is literally [17 lines of HTML](https://github.com/18F/chat/blob/master/index.html) and a Google Form...I think we're going a bit overboard here.

@gboone How would you feel about Outreach adopting the app, with the understanding that I do any required maintenance for as long as I'm around?

**Comment by gboone** [comment]
We've never been involved with chat.18f.gov or any decisions around the process of bringing in new guest users who request access through the site. What would adopting/owning it mean?

**Comment by jmcarp** [comment]
Ping @afeld @brittag.

My two cents: owning such a small "application" should be very lightweight, but *somebody* has to do it if we're going to keep it around. It seems like the owner should be whoever responds to requests we get on the google form. Owning an app like this would probably entail cycling deployer account credentials when they expire, and not much else.

**Comment by brittag** [comment]
Agree with @jmcarp - it needs to have a person who is responsible for it, even if it's super tiny.

**Comment by afeld** [comment]
Ah. In that case, I'm happy to be that person. Will try and pick this up soon.

**Comment by afeld** [comment]
Thought of an even easier solution: deploying via Federalist. https://github.com/18F/chat/pull/13

Thanks for the work on this though, @jmcarp!

**Comment by afeld** [comment]
Deleted the `chat-deployer` service instance in GovCloud.

**Pull request closed without merging**
